version: '3'

services:
  # Nodo MySQL 1 (Master)
  mysql1:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_REPLICATION_USER=replica
      - MYSQL_REPLICATION_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    volumes:
      - mysql1-data:/var/lib/mysql
      - ../init-files/init.sql:/tmp/init.sql  # Montaje del archivo init.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb

  # Nodo MySQL 2 (Slave)
  mysql2:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_REPLICATION_USER=replica
      - MYSQL_REPLICATION_PASSWORD=root
    networks:
      - mysql_network
    volumes:
      - mysql2-data:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --relay-log=mysql-relay-bin --read-only=1 --binlog-do-db=testdb

  # Nodo MySQL 3 (Slave)
  mysql3:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_REPLICATION_USER=replica
      - MYSQL_REPLICATION_PASSWORD=root
    networks:
      - mysql_network
    volumes:
      - mysql3-data:/var/lib/mysql
    command: --server-id=3 --log-bin=mysql-bin --relay-log=mysql-relay-bin --read-only=1 --binlog-do-db=testdb

  # HAProxy para balanceo de carga
  haproxy:
    image: haproxy:latest
    ports:
      - "3307:3306"  # Puerto de balanceo de carga (MySQL balanceado en puerto 3307)
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # Montaje de archivo haproxy.cfg
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql1-data:
  mysql2-data:
  mysql3-data:
