-- =====================================
-- SENTENCIAS DE COMPROBACIÓN
-- =====================================

SELECT * FROM PAIS;
SELECT * FROM SEDE;
SELECT * FROM DEPORTE;
SELECT * FROM DISCIPLINA;
SELECT * FROM PARTICIPANTE;
SELECT * FROM ATLETA;
SELECT * FROM EQUIPO;
SELECT * FROM CUERPO_TECNICO;
SELECT * FROM FISIOTERAPEUTA;
SELECT * FROM ENTRENADOR;
SELECT * FROM PSICOLOGO;
SELECT * FROM MEDALLA;
SELECT * FROM EVENTO;
